SELECT EMP1.employee_id AS EMP_SANTA, 
EMP1.first_name AS  FIRST_NAME_SANTA, 
EMP1.LAST_name AS  LAST_NAME_SANTA,
EMP2.employee_id AS EMP_NAME, 
EMP2.first_name AS  FIRST_NAME, 
EMP2.LAST_name AS  LAST_NAME 
FROM employee_salary EMP1
JOIN EMPLOYEE_SALARY EMP2
	ON EMP1.EMPLOYEE_ID + 1 = EMP2.EMPLOYEE_ID
;
